version: '3'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    volumes:
      - /home/sysop/iot-infra/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /home/sysop/iot-infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: bridge
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: bridge
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  nginx:
    container_name: nginx_rvrs_proxy
    image: nginx:latest
    volumes:
      - /home/sysop/iot-infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
    depends_on:
      - grafana
      - esphome 

  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    restart: always
    network_mode: bridge
    environment:
      # password for Web GUI
      - PASSWORD=wireguard123
      # physical public IP so the QR codes know where to route
      - WG_HOST=22.99.88.222
    ports:
      # UDP port for the actual VPN tunnel
      - "51820:51820/udp"
      # TCP port only for accessing the Web GUI via NGINX
      - "51821:51821/tcp"
    volumes:
      # Bind mount to save the generated QR codes and keys to the host
      - /home/sysop/iot-infra/wireguard:/etc/wireguard
      # Bind mount for time sync to prevent replay attacks
      - /etc/localtime:/etc/localtime:ro
      # Bind mount allowing the container to access Debian's networking hardware
      - /lib/modules:/lib/modules:ro
    cap_add:
      # Capability Add: Grants authority to create virtual network interfaces
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      # Modifies the Debian kernel to act as a router for the VPN traffic
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  grafana_data:




# All containers for observability stack have been deployed - 4/6/2026 10PM
# All docker containers are up (esphome, grafana, prometheus) - 4/6/2026 10PM
# All docker containers are up (esphome, grafana, prometheus, NGINX) - 4/7/2026 11:05PM





































