events {
    worker_connections 1024; # 1024 sumultanerous network connections allowed per CPU thread by nginx engine
}

# Master block telling nginx we are processing web traffic - L7
http {
    # Server Block for Grafana
    server { # defining parameters for grafana
        listen 80;
        server_name grafana.local;
	# NGINX server is being told to listen on port 80 (http) for FQDN 'grafana.local' in traffic's HTTP header
	# the traffic on port 80 would be a result of you typing the domain in the web browser

        location / { # the routing rule for the URL path, '/' means "catch all traffic sent to the root domain"
            proxy_pass http://192.168.68.66:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
	    # last 2 lines force NGINX to fwd laptops actual IP to grafana for accurate security logging
	    # telling NGINX server engine to route the traffic coming on port 80 to physical server ip:port for grafana
        }
    }

    # Server Block for ESPHome
    server { # defining parameters for esphome
        listen 80;
        server_name esphome.local;
	# nginx server enginer being told to listen on port 80 for esphome.local FQDN

        location / { # telling nginx server engine to route traffic to the physical server ip:port for esphome
            proxy_pass http://192.168.68.66:6052;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade; # esphome relies on websockets (persistent, real-time connection), this tells NGIN to 'upgrade' connection to persistent websocket so ESPHome dashboard doesnt constatnly disconnect
            proxy_set_header Connection "upgrade"; # this forces NGINX to honor the upgrade, w/o this it would just sever the connection after first line of text is loaded
        }
   
    }


    # Server Block for Pi-Hole so NGINX routes to domain on port 8080 instead of 80/443 
    server {
	listen 80;
	server_name pihole.local
	
	location / {
	    proxy_pass http://192.168.68.66:8080;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	}

    }
}
