version: '3'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    volumes:
      - /home/sysop/iot-infra/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /home/sysop/iot-infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: bridge
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: bridge
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  grafana_data:

# All containers for observability stack have been deployed - 4/6/2026 10PM
# All docker containers are up - 4/6/2026 10PM






































